name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:

    inputs:
      infile:
        description: The YAML file to be updated
        default: 'test.yaml'
        required: false
      varlist:
        description: Comma separated list of var=value
        default: ''
        required: true
      exclude_varname:
        description: Exclude the variable name in the returned values. Note the values returned are in the order they are found.
        default: false
        required: false
    outputs:
      values:
        description: 'Returns a comma separated list of found <variable>=<value> values'
        value: ${{ steps.get-yaml-value.outputs.values }}
        
jobs:
  yamloutput:
    runs:
      using: "composite"
      steps:
        - uses: actions/setup-python@v4
          with:
            python-version: '3.9'
        - run: 
            python ${{ github.action_path }}/get-yaml-value.py -i ${{ inputs.infile }} -V "${{ inputs.varlist }}" -x ${{ inputs.exclude_varname }}
          shell: bash
          id: get-yaml-value
 
