name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: get-yaml-value
      uses: rmeneely/get-yaml-value@v1
      with:
        infile: test.yaml
        varlist: runOrder,runPlanOnly

 
