on:
 push:
  branches:
    - main
 workflow_dispatch:
   inputs:
     infile:
       description: The YAML file to be updated
       default: 'test.yaml'
       required: false
     varlist:
       description: Comma separated list of var=value
       default: ''
       required: true
     exclude_varname:
       description: Exclude the variable name in the returned values. Note the values returned are in the order they are found.
       default: false
       required: false


jobs:
  yaml:
    runs-on: ubuntu-latest
    name: yaml-input    
    steps:
      - name: Get yaml input value
        uses: actions/setup-python@v4
        id: get-yaml-value
        with:
         python-version: '3.9'
         run: python ${{ github.action_path }}/get-yaml-value.py -i ${{ inputs.infile }} -V "${{ inputs.varlist }}" -x ${{ inputs.exclude_varname }}
         shell: bash
  yamlop:
    runs-on: ubuntu-latest
    outputs:
       value: ${{ steps.get-yaml-value.outputs.values }}
    
          
   
     
