on:
 push:
  branches:
    - main
    
jobs:
  yaml:
    runs-on: ubuntu-latest
    name: yaml-input    
    steps:
    
        - name: Read yaml file
          uses: rmeneely/get-yaml-value@v1
          id: getyaml
          with:
            infile: './test.yaml'
            varlist: ''
            exclude_varname: false
       
        - name: Get yaml input value
          run : echo ${{ steps.getyaml.outputs.values }}
         
          
   
     
